spring.application.name=gateway-service
server.port=8000
spring.cloud.discovery.enabled=true
#pour ne pas avoir les logs de config parce que nous n'avons pas encore de service config
spring.cloud.config.enabled=false